### ISSUE TITLE
Batch convert.

### ISSUE THREAD

**Issue by Zetavio** [discully/afinalunity#1]
Is it possible to batch convert the VAC files? I attempted a wildcard, but the program told me I was opening 2 files at the same time and wouldn't let that happen.

**Comment by discully** [comment]
I've just added support to afu_to_wav.py to [allow multiple audio files to be specified](https://github.com/discully/afinalunity/commit/cee8c01633c4c236b81b2f7891a8174b43ecafc4).
That should allow the use of wildcards on the command line, except on Windows (that would be a bit more work, but do say if that's what you need).
Let me know if that works for you.

**Comment by Zetavio** [comment]
Thank you Discully.    I came here to remove my request because I found a work around using a batch file.  Then i see you already did the change! I appreciate your help.

**Comment by discully** [comment]
No problem. Glad it's of some use to you.
