### ISSUE TITLE
Subtitle Character Names

### ISSUE THREAD

**Issue by pgodwin** [discully/afinalunity#3]
Firstly thanks for this project, it's terrific!

One (hopefully) quick question. Is it possible to have the characters name for the subtitle export? I couldn't see an easy way to modify the code, but I'm not familiar with the structure of the files.

**Comment by discully** [comment]
Glad you're finding the project useful. I'm afraid the .bst processing code is a bit of a mess, so not surprised you couldn't see and easy way to modify it.

I'm not convinced I want to stick with this approach but, for now, I think I've added in what you need. You should see an extra option available for `afu_subtitles.py`. If you add `--names` as an argument, it will output both the subtitle text and the speaker's name in the file.

I'm going to leave this ticket open for now, whilst I decide if I want to stick to this approach. Let me know if it works for you.

**Comment by discully** [comment]
I haven't had time to come back to this. But the solution posted works well enough, so I'll close the issue.
